name: test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@2.0.1
        with:
          version: 6.11.5
      - name: Install Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm --frozen-lockfile

      - name: Run lint
        run: pnpm lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['10', '12', '14']

    steps:
      - name: Setup Git
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@2.0.1
        with:
          version: 6.11.5

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm test:coverage --ci --reporters="default" --reporters="jest-junit"

      - name: Publish code coverage report
        uses: codecov/codecov-action@v1
        with:
          name: codecov
